version: '3'

volumes:
  app:
  db:

services:

  db:
    image: mysql

    expose:
      - 3306

    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: 'planing'
      MYSQL_USER: 'planing_admin'
      MYSQL_PASSWORD: 'F13DVO82S1YTj9yQAm'
      MYSQL_ROOT_PASSWORD: '4z9AFpQMtpCsRJHKUe'

    volumes:
      - db:/var/lib/mysql

    restart: always

  app:
    build: ./app

    expose:
      - 80

    ports:
      - '8888:80'

    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        python /app/manage.py makemigrations accounts
        python /app/manage.py makemigrations events
        python /app/manage.py makemigrations participants
        python /app/manage.py migrate
        python /app/manage.py runserver 0.0.0.0:80
    volumes:
      - app:/app

    depends_on:
      - db

    restart: always
